PREP(moduleAoeHint);
PREP(moduleBodyLoot);
PREP(moduleColorCorrection);
PREP(moduleEditorDynamicSimulation);
PREP(moduleFuelConsumption);
PREP(moduleUnarmed);
PREP(moduleCharacters);
PREP(moduleUnitSpawner);
PREP(initSpawnerModules);