//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 210.149954 on Stable branch
// Generated with ALiVE version 1.17.0.2209061
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses
{
  class GVAR(Mrazota)
  {
    displayName = "[JAGER] Mrazota";
    side = 0;
    flag = "";
    icon = "";
    priority = 3;
  };
};

class CfgVehicles
{
  class EventHandlers;

  // Melee fists.
  class O_soldier_Melee_fists;
  class GVAR(Mrazota_Melee_Fists) : O_soldier_Melee_fists
  {
    faction = QGVAR(Mrazota);
    displayName = "Melee Fists";
#include "CfgVehiclesRandomizedGear.hpp"
  };

  // Melee fists rusher.
  class O_soldier_Melee_RUSH_fists;
  class GVAR(Mrazota_Melee_Fists_Rusher) : O_soldier_Melee_RUSH_fists
  {
    faction = QGVAR(Mrazota);
    displayName = "Melee Fists Rusher";
#include "CfgVehiclesRandomizedGear.hpp"
  };

  // Melee weapon.
  class O_soldier_Melee;
  class GVAR(Mrazota_Melee_Weapon) : O_soldier_Melee
  {
    faction = QGVAR(Mrazota);
    displayName = "Melee Weapon";
#include "CfgVehiclesRandomizedGear.hpp"
  };

  // Melee weapon rusher.
  class O_soldier_Melee_RUSH;
  class GVAR(Mrazota_Melee_Weapon_Rusher) : O_soldier_Melee_RUSH
  {
    faction = QGVAR(Mrazota);
    displayName = "Melee Weapon Rusher";
#include "CfgVehiclesRandomizedGear.hpp"
  };

  // Hybrid.

  // Shooter.
};
